# This workflow updates GitHub Pages on the repo it is run from.

name: Update GitHub Pages

on:
  workflow_dispatch:  # Manually trigger. Colon is required.
  workflow_call: # Allow this workflow to be called from publish workflow.

permissions:
  contents: write  # For checkout and push.

jobs:
  update-github-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0

    - name: NPM install
     
      run: |
        ls -l
        npm ci
        npm install gh-pages --save-dev
    - name: Deploy to GH Pages
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # deploys to the current repo,
      # so you can use this workflow from a fork to update your personal gh-pages
      run: |
        git config --global user.email "xaisuite@gmail.com"
        git config --global user.name "S Mitra"
        git remote set-url origin https://git:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run-script deploy build -m "Deploy Node.js app to GitHub Pages"
